name: flutter_matrix
description: The matrix class designed for Flutter can also be used in pure Dart, 
  and is also a full-platform alternative to the Matply library. 
  It supports basic matrix operations, linear algebra, probability
  theory and mathematical statistics, geometric simulation, central difference, etc.
homepage: https://pythonnotjava.github.io//src/pkg/Flutter_Matrix/site
repository: https://github.com/PythonnotJava/flutter_matrix
documentation: https://pythonnotjava.github.io//src/pkg/Flutter_Matrix/site
issue_tracker: https://github.com/PythonnotJava/flutter_matrix/issues

version: 0.1.1

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  collection: ^1.19.1

topics:
  - matrix
  - random
  - linalg
  - math

platforms:
  windows:
  android:
  linux:
  ios:
  macos:
  web: