name: flutter_matrix
description: A Flutter-friendly matrix library for Dart, offering basic operations, linear algebra, probability, statistics, geometry, and more.
homepage: https://pythonnotjava.github.io//src/pkg/Flutter_Matrix/site
repository: https://github.com/PythonnotJava/flutter_matrix
documentation: https://pythonnotjava.github.io//src/pkg/Flutter_Matrix/site
issue_tracker: https://github.com/PythonnotJava/flutter_matrix/issues

version: 0.1.4

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  collection: ">=1.19.1"

topics:
  - matrix
  - random
  - linalg
  - math

platforms:
  windows:
  android:
  linux:
  ios:
  macos:
  web: